### ISSUE TITLE
Project Only Shows Error Page

### ISSUE THREAD

**Issue by DaGeRe** [t2-project/devops#16]
After starting the project using `docker compose up &> logs.txt`, the only thing that is shown is the `Whitelabel Error Page`. 

The logs are here:
[logs.txt](https://github.com/user-attachments/files/17258246/logs.txt)

**Comment by davidkopp** [comment]
The issue was only related to the UI.
I added the missing dependency for both variants, modulith and microservices:
- https://github.com/t2-project/modulith/commit/3e5ec4c94832ff1746c6ad0c9666edfbfa6e3dc0
- https://github.com/t2-project/ui/commit/ed3bb34abb3ce1108e66ed59a62d7ab6fc5bd793

**Comment by DaGeRe** [comment]
Thanks, that fixed it. 

Unfortunately, this is only fixed after manually checking out the main branch in the modulith module, and pulling it - is it possible that the project containing the submodules would also need upgrading?

**Comment by davidkopp** [comment]
The parent projects [t2-project](https://github.com/t2-project/t2-project) and [microservices](https://github.com/t2-project/microservices) are already up-to-date. Either execute `git pull --recurse-submodules` or `git submodule update --recursive` to update the sub modules.

I have now added a branch to the submodule configuration so `git submodule update --recursive --remote` also works (https://stackoverflow.com/a/18797720).
